[10:57:33][ERROR] status.fgis_worker fgis_worker.py:get_status:47 | error: list index out of range
